### ISSUE TITLE
方便交流一下

### ISSUE THREAD

**Issue by zyc751201** [Chen-Zehao12/Text-Classification-using-Paddle#1]
你好，我看到你这个项目，有这个方面的问题需要请教一下？方便加一下QQ：271168735

**Comment by Chen-Zehao12** [comment]
你好，可以直接通过邮箱进行交流。我也是初学者，可能只能尽力。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chen-Zehao12/Text-Classification-using-Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 凌晨0:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Chen-Zehao12/Text-Classification-using-Paddle] 方便交流一下 (Issue #1)





 
你好，我看到你这个项目，有这个方面的问题需要请教一下？方便加一下QQ：271168735

**Comment by CodingMonkey12** [comment]
你好，可以通过QQ邮箱进行交流，我也是初学者，可能只能尽力。366456863@qq.com
